sudo: false
language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-feathers-plugin' ]; then cd .. && eval "mv $currentfolder generator-feathers-plugin" && cd generator-feathers-plugin; fi
